language: python
sudo: false
cache: pip
env:
  - COVERALLS_REPO_TOKEN="RbnaxzEouDqGe0oNVwEP4TBS0sL20ZpGg"
before_install:
  - python3 -m pip install -r requirements.txt
install:
  - python3 -m pip install .
script:
  - python3 -m pytest
after_success:
  - coveralls
