language: python
sudo: false
cache: pip
matrix:
  include:
  - python: '3.5'
    env: DEPS="numpy scipy matplotlib pandas"
  - python: '3.6'
    env: DEPS="numpy scipy matplotlib pandas"
before_install:
- if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh
  -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh
  -O miniconda.sh; fi
- chmod +x miniconda.sh
- "./miniconda.sh -b -p /home/travis/mc"
- export PATH=/home/travis/mc/bin:$PATH
install:
- conda update --yes conda
- conda config --add channels soft-matter
- conda create -n testenv --yes $DEPS pip nose setuptools python=$TRAVIS_PYTHON_VERSION
- source activate testenv
- echo $PATH
- which python
- conda info
- conda list
- python setup.py install
script: nosetests --with-coverage
after_success:
- coveralls
deploy:
  provider: pypi
  user: saroele
  password:
    secure: rdYPG+vZA2qLX8/r0ocZX438nIY3DIrpNqbtJJtf3Z8qLlJ/LzZsF73CMyhZgB1c/hHoXjteAHPS+I3mt4uELX+81K9V4Q7SEOUg9W5CY2fo8ah8R9qkVcN/DZhweV+5A4fpfAYp2Sp2uq4wYKrPtz3wyqyqdfG3DNnWdXN3nAGPwShYWBqyyBq9RkxRKVozyVZhtWr8/i4ZJv8mOI+83H2ikagYx1m/nPMC89Szme5ojTuOGkYptQn19VOkZkDpuUaeuefqXWT5vwNMzKu46Srnktt5m5H9oj6HxcfzFGVmsOtqSXUr1HQccGlYHCKetZlNu/nKe8eHoXl8pdRl6ChiTQyRDgDQLEAM2423aPDrxHLgcQ198As0rpVJoh2C1hz02IkYgl5U0ulhRqA3Fq6GRHgB6glUakoKVDQdQCREjc8KBZ893ThcsNyWMA94KQj/KKFTa//zg+qBF9rpyBNmOlJAABMzUPv6Mi75GYOA4xE73NK3SABJI3qss07UyJea+z8y6aWkxlf6kN/ZkC1Ne5OX3ZYSJ+bJvvIgjTt7d/TAL+x2yhymjBmolLFoBotFthaLJ4n/O0Z4seeDNCDkPOlW/clWF7JNukuvi/2ppnJMUmxcFbYbYMgTR4hCbkQ1vuH56UimoG4iewdLe0SIJitFQzrbyPynTwvv93o=
  on:
    tags: true
    branch: master
