language: python
sudo: false
cache: pip
matrix:
  include:
    - python: "3.5"
    - python: "3.6"
before_install:
  - python3 -m venv venv
  - source ./venv/bin/activate
  - python3 -m pip install -r requirements.txt
install:
  - python3 -m pip install .
script:
  - python3 -m pytest
after_success:
  - coveralls
