language: python
sudo: false
cache: pip
env:
  - COVERALLS_REPO_TOKEN="RbnaxzEouDqGe0oNVwEP4TBS0sL20ZpGg"
matrix:
  include:
    - python: "3.5"
    - python: "3.6"
before_install:
  - python3 -m pip install -r requirements.txt
install:
  - python3 -m pip install .
script:
  - coverage run -m pytest
after_success:
  - coveralls
