language: python
sudo: false
cache: pip
matrix:
  include:
    - python: "3.5"
    - python: "3.6"
before_install:
  - python3 -m pip install wheel pytest
install:
  - python3 -m pip install .
script:
  - python3 -m pytest
after_success:
  - coveralls
