language: python
sudo: false
cache: pip
matrix:
  include:
    - python: "3.5"
      env: DEPS="numpy scipy matplotlib pandas"
    - python: "3.6"
      env: DEPS="numpy scipy matplotlib pandas"
before_install:
  - python3 -m pip install wheel
install:
  - python3 -m pip install .
script: nosetests --with-coverage
after_success:
  - coveralls
